# Generated by Django 4.2.4 on 2023-08-18 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('user_name', models.CharField(max_length=100, unique=True)),
                ('user_mail', models.EmailField(max_length=254, unique=True)),
                ('mobile_number', models.IntegerField(unique=True)),
                ('password', models.CharField(max_length=15)),
                ('re_password', models.CharField(max_length=15)),
            ],
        ),
    ]
